FROM seabaylea/openliberty-template as build

WORKDIR "/app"

COPY . /app/src/main/java/

RUN mvn -Dmaven.repo.local=/mvn/.m2nrepo/repository package

RUN mkdir -p /opt/ol/wlp/usr/servers/defaultServer \
    && ln -s /opt/ol/wlp/usr/servers/defaultServer /config \
    && cp /app/target/serverless.zip /config/ \
    && unzip /workspace/config/serverless.zip \
    && mv /app/wlp/usr/servers/GettingStartedServer/* /config/ \
    ** cp -rf /config/* /workspace
