FROM seabaylea/openliberty-template

WORKDIR "/app"

COPY . /app/src/main/java/

RUN mvn -Dmaven.repo.local=/mvn/.m2nrepo/repository package

RUN mkdir -p /opt/ol/wlp/usr/servers/defaultServer \
    && ln -s /opt/ol/wlp/usr/servers/defaultServer /config \
    && cp /app/target/serverless.zip /config/ \
    && unzip /config/serverless.zip \
    && mv /app/wlp/usr/servers/GettingStartedServer/* /config/

FROM open-liberty
COPY --from=0 /config/ /config

ENV PORT 8080
EXPOSE $PORT 9443
